### ISSUE TITLE
Issue when running demo

### ISSUE THREAD

**Issue by mikechn** [flashbots/ethers-provider-flashbots-bundle#86]
Hi,

I got this error when running demo. I have tried different versions of NodeJs, but neither worked.
![flashbots_error1](https://user-images.githubusercontent.com/29853619/209572891-665a2c1f-fcd4-4d0f-8066-d300b0014c16.PNG)

**Comment by zeroXbrock** [comment]
hey @mikechn thanks for raising this. It looks like your environment is not populated with the required variables (the error on line 30 should be due to FLASHBOTS_AUTH_KEY not being set). The [script has been updated](https://github.com/flashbots/ethers-provider-flashbots-bundle/pull/87/commits/6023b3571b9f92df52ce4d608fd11b0709295243) to check these vars for you -- try running again with the latest release and it will tell you what you're missing.

Closing this now but feel free to re-open if this doesn't solve your issue.
